blogicum/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.index, name="index"),
    path("posts/<int:id>/", views.post_detail, name="post_detail"),
    path(
        "category/<slug:category_slug>/",
        views.category_posts,
        name="category_posts",
    ),
]

blogicum/blogicum/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("blog.urls")),
    path("pages/", include("pages.urls")),
    path("admin/", admin.site.urls),
]

blogicum/pages/urls.py
from django.urls import path
from . import views

app_name = "pages"

urlpatterns = [
    path("about/", views.about, name="about"),
    path("rules/", views.rules, name="rules"),
]

blogicum/blog/views.py
from django.shortcuts import render

posts = [
    {
        "id": 0,
        "location": "Остров отчаянья",
        "date": "30 сентября 1659 года",
        "category": "travel",
        "text": """Наш корабль, застигнутый в открытом море
                страшным штормом, потерпел крушение.
                Весь экипаж, кроме меня, утонул; я же,
                несчастный Робинзон Крузо, был выброшен
                полумёртвым на берег этого проклятого острова,
                который назвал островом Отчаяния.""",
    },
    {
        "id": 1,
        "location": "Остров отчаянья",
        "date": "1 октября 1659 года",
        "category": "not-my-day",
        "text": """Проснувшись поутру, я увидел, что наш корабль сняло
                с мели приливом и пригнало гораздо ближе к берегу.
                Это подало мне надежду, что, когда ветер стихнет,
                мне удастся добраться до корабля и запастись едой и
                другими необходимыми вещами. Я немного приободрился,
                хотя печаль о погибших товарищах не покидала меня.
                Мне всё думалось, что, останься мы на корабле, мы
                непременно спаслись бы. Теперь из его обломков мы могли бы
                построить баркас, на котором и выбрались бы из этого
                гиблого места.""",
    },
    {
        "id": 2,
        "location": "Остров отчаянья",
        "date": "25 октября 1659 года",
        "category": "not-my-day",
        "text": """Всю ночь и весь день шёл дождь и дул сильный
                порывистый ветер. 25 октября.  Корабль за ночь разбило
                в щепки; на том месте, где он стоял, торчат какие-то
                жалкие обломки,  да и те видны только во время отлива.
                Весь этот день я хлопотал  около вещей: укрывал и
                укутывал их, чтобы не испортились от дождя.""",
    },
]


def index(request):
    context = {
        'posts': posts[::-1]
    }
    return render(request, 'blog/index.html', context)


def post_detail(request, id):
    post = next((p for p in posts if p['id'] == id), None)
    context = {
        'post': post
    }
    return render(request, 'blog/detail.html', context)


def category_posts(request, category_slug):
    context = {
        'category': category_slug
    }

    return render(request, 'blog/category.html', context)

blogicum/pages/views.py
from django.shortcuts import render


def about(request):
    return render(request, 'pages/about.html')


def rules(request):
    return render(request, 'pages/rules.html')

blogicum/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Блогикум</title>
</head>
<body>
    <h1><a href="{% url 'blog:index' %}">Блогикум</a></h1>
    <hr>
    {% block content %}{% endblock %}
    <hr>
    <p>© Блогикум</p>
</body>
</html>

blogicum/templates/blog/category.html
{% extends "base.html" %}

{% block content %}

<h2>Публикации в категории - {{ category }}</h2>

{% endblock %}

blogicum/templates/blog/detail.html
{% extends "base.html" %}

{% block content %}

<p><b>Место:</b> {{ post.location }}</p>
<p><b>Дата:</b> {{ post.date }}</p>
<p><b>Категория:</b> {{ post.category }}</p>

<p>{{ post.text }}</p>

{% endblock %}

blogicum/templates/blog/index.html
{% extends "base.html" %}

{% block content %}
<h2>Лента записей</h2>

{% for post in posts %}
    <p><b>Место:</b> {{ post.location }}</p>
    <p><b>Дата:</b> {{ post.date }}</p>
    <p><b>Категория:</b>
        <a href="{% url 'blog:category_posts' post.category %}">
            {{ post.category }}
        </a>
    </p>
    <p>{{ post.text|truncatewords:10 }}</p>
    <a href="{% url 'blog:post_detail' post.id %}">Читать полный текст</a>
    <hr>
{% endfor %}

{% endblock %}

blogicum/templates/pages/about.html
{% extends "base.html" %}

{% block content %}
<h2>О проекте</h2>
<p>Это социальная сеть для личных дневников.</p>
{% endblock %}

blogicum/templates/pages/rules.html
{% extends "base.html" %}

{% block content %}
<h2>Правила</h2>
<p>Будьте вежливы и не спамьте.</p>
{% endblock %}